spring:
  application:
    name: elastic
  profiles:
    active: local
  data:
#  elk配置
    elasticsearch:
      cluster-name: es-test
      cluster-nodes: 13.14.100.67:9300
#  es配置
  elasticsearch:
    jest:
      uris: http://13.14.100.67:9200
      read-timeout: 20000
      connection-timeout: 20000